#! /bin/bash
if [ $# -ge 3 ]; then
	inputFile=$1
	inputSize=$2
	verLevel=$3
elif [ $# -ge 2 ]; then
	inputFile=$1
	inputSize=$2
	verLevel=0
elif [ $# -eq 1 ]; then
	inputFile=$1
	inputSize=512
	verLevel=0
else
	#inputFile="advmap1.c"
	inputFile="specmap.c"
	inputSize=32
	verLevel=0
fi

openarcrt="../../../../openarcrt"
openarclib="../../../../lib"

if [ ! -f "$inputFile" ]; then
	echo "====> The input file, $inputFile does not exist; use the default intput file (advmap1.c)"
    cp "advmap1.c" "advmap.c"
else
    cp "$inputFile" "advmap.c"
fi

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$inputSize" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__inputSize__|${inputSize}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt advmap.c
echo ""
#echo "====> To compile the translated output file:"
#echo "\$ make"
#echo ""
#echo "====> To run the compiled binary:"
#echo "\$ cd bin; advmap_ACC"
#echo ""
