/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class NVL {
  public static void LLVMAddNVLAddTxsPass(SWIGTYPE_p_LLVMOpaquePassManager PM) {
    NVLJNI.LLVMAddNVLAddTxsPass(SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddNVLHoistTxAddsPass(SWIGTYPE_p_LLVMOpaquePassManager PM, boolean aggressive) {
    NVLJNI.LLVMAddNVLHoistTxAddsPass(SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(PM), aggressive);
  }

  public static void LLVMAddNVLAddSafetyPass(SWIGTYPE_p_LLVMOpaquePassManager PM) {
    NVLJNI.LLVMAddNVLAddSafetyPass(SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddNVLAddRefCountingPass(SWIGTYPE_p_LLVMOpaquePassManager PM) {
    NVLJNI.LLVMAddNVLAddRefCountingPass(SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddNVLAddPersistsPass(SWIGTYPE_p_LLVMOpaquePassManager PM) {
    NVLJNI.LLVMAddNVLAddPersistsPass(SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddNVLLowerPointersPass(SWIGTYPE_p_LLVMOpaquePassManager PM) {
    NVLJNI.LLVMAddNVLLowerPointersPass(SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(PM));
  }

}
