/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class NVLJNI {
  public final static native void LLVMAddNVLAddTxsPass(long jarg1);
  public final static native void LLVMAddNVLHoistTxAddsPass(long jarg1, boolean jarg2);
  public final static native void LLVMAddNVLAddSafetyPass(long jarg1);
  public final static native void LLVMAddNVLAddRefCountingPass(long jarg1);
  public final static native void LLVMAddNVLAddPersistsPass(long jarg1);
  public final static native void LLVMAddNVLLowerPointersPass(long jarg1);
}
