/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class SupportJNI {
  public final static native int LLVMLoadLibraryPermanently(String jarg1);
  public final static native void LLVMUnloadLibraries();
}
