#! /bin/bash
if [ $# -ge 3 ]; then
	inputFile=$1
	inputSize=$2
	blockSize=$3
elif [ $# -eq 2 ]; then
	inputFile=$1
	inputSize=$2
	blockSize=8
elif [ $# -eq 1 ]; then
	inputFile=$1
	inputSize=512
	blockSize=8
else
	inputFile="matmul.c_v0"
	inputSize=512
	blockSize=8
fi

verLevel=0
openarcrt="../../../../openarcrt"
openarclib="../../../../lib"

if [ ! -f "$inputFile" ]; then
    echo "====> The input file, $inputFile does not exist; use the default intput file (matmul.c_v0)"
    cp "matmul.c_v0" "matmul.c"
else
    cp "$inputFile" "matmul.c"
fi


if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$inputSize" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__inputSize__|${inputSize}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$blockSize" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__blockSize__|${blockSize}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt *.c
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; matmul_ACC"
echo ""
