#! /bin/bash
if [ $# -ge 2 ]; then
	inputSrc=$1
	verLevel=$2
elif [ $# -eq 1 ]; then
	inputSrc=$1
	verLevel=0
else
	inputSrc=reduction1.c
	verLevel=0
fi

openarcrt="${openarc}/openarcrt"
openarclib="${openarc}/lib"

if [ -f "${inputSrc}" ]; then
    cp "${inputSrc}" "reduction.c"
fi

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt reduction.c 
rm -f reduction.c

HNAME=`uname -s | cut -d"." -f1`
if [ $HNAME = "Darwin" ]; then
	cd cetus_output
    mv "openarc_kernel.cl" "openarc_kernel_tmp.cl"
    cat "openarc_kernel_tmp.cl" | sed "s|1\.7976931348623158e+308|3\.402823466e+38|g" > "openarc_kernel.cl"
    mv "openarc_kernel.cl" "openarc_kernel_tmp.cl"
    cat "openarc_kernel_tmp.cl" | sed "s|2\.2250738585072014e-308|1\.175494351e-38|g" > "openarc_kernel.cl"
    rm "openarc_kernel_tmp.cl"
	cd ../
fi
