#!/bin/bash

OUTPUT=$1
STEP=$2

NVPROF="nvprof --events l2_subp0_write_sector_misses,l2_subp1_write_sector_misses,l2_subp0_total_write_sector_queries,l2_subp1_total_write_sector_queries,l2_subp0_read_sector_misses,l2_subp1_read_sector_misses,l2_subp0_total_read_sector_queries,l2_subp1_total_read_sector_queries"

EXEC=./OMP_CUDART


if [ $STEP -eq 0 ] ; then
	#for APP in JACOBI SPARSELU HEAT SW SAT DTW INT SNAP;
  for APP in JACOBI;
	do
		# for SCHED_POLICY in RR LF AL;
		for SCHED_POLICY in RR LF;
		do
			./switchApp $APP $SCHED_POLICY

			if [ $APP == "JACOBI" ] ; then
				dataSize=21504
				tbSize=512
			elif [ $APP == "SPARSELU" ] ; then
				dataSize=8192
				tbSize=512
			elif [ $APP == "HEAT" ] || [ $APP == "INT" ] || [ $APP == "SAT" ] ; then
				#define QUEUE_LENGTH 2048
				#define QUEUE_BUFFER_LENGTH 16
				#define MAX_WORKERS 64
				#define N_WORKERS 56
				#define POLL_CYCLES_WORKER 2
				dataSize=46080
				tbSize=512
			elif [ $APP == "SW" ] || [ $APP == "DTW" ] ; then
				#define QUEUE_LENGTH 8192
				#define QUEUE_BUFFER_LENGTH 16
				#define MAX_WORKERS 64
				#define N_WORKERS 56
				#define POLL_CYCLES_WORKER 2
				dataSize=46080
				tbSize=640=
			fi

				for count in 1 2 3 4 5;
				do
					COMMAND="$EXEC -n $dataSize -b $tbSize -r 1 -i 1 -d 1 -a $APP -s $SCHED_POLICY"
					echo $COMMAND >> $OUTPUT.$APP
					( set -x ; $COMMAND  >> $OUTPUT.$APP )
				done
				( set -x ; $NVPROF $COMMAND  >>$OUTPUT.PROF.$APP 2>>$OUTPUT.PROF.$APP )
		done

		# do it for global as well
		for count in 1 2 3 4 5;
		do
			COMMAND="$EXEC -n $dataSize -b $tbSize -r 1 -i 1 -d 2 -a $APP -s $SCHED_POLICY"
			echo $COMMAND >> $OUTPUT.$APP
			( set -x ; $COMMAND  >> $OUTPUT.$APP )
		done
		( set -x ; $NVPROF $COMMAND  >>$OUTPUT.PROF.$APP 2>>$OUTPUT.PROF.$APP )
	done
fi

if [ $STEP -eq 1 ] ; then
	for APP in DTW HEAT INT JACOBI SAT SW;
	do
		echo $APP
		egrep 'execTime' out9.$APP | awk -F '\t' '{print $2}'
	done
fi

if [ $STEP -eq 10 ] ; then
	nvprofstring="nvprof --metrics l2_l1_read_hit_rate"

	echo "# EXP.2 PROFILE" >> $OUTPUT
	for APP in DTW HEAT2D SAT SW;
	do
		for tbSize in 1024;
		do
			./switchApp $APP 0
			$nvprofstring $EXEC  --mode=0 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			$nvprofstring $EXEC  --mode=1 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			$nvprofstring $EXEC  --mode=2 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			$nvprofstring $EXEC  --mode=3 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			./switchApp $APP 1
			$nvprofstring $EXEC  --mode=0 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			$nvprofstring $EXEC  --mode=1 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			$nvprofstring $EXEC  --mode=2 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
			$nvprofstring $EXEC  --mode=3 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tbSize --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT 2>>$OUTPUT
		done
	done
fi



if [ $STEP -eq 2 ] ; then
	echo "# EXP.3 SYNC INTERVAL" >> $OUTPUT
	tbSize=1024
	for APP in DTW HEAT2D SAT SW;
	do
		./switchApp $APP 1
		for tileWidth in 2 4 8 16 32 64 128 256 512 1024;
		do
			#$EXEC mode=1 rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tileWidth --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT
			echo $APP $tileWidth
			$EXEC --mode=3 --rowsPerBlock=1 --width=46080 --height=46080 --tileWidth=$tileWidth --tileHeight=$tbSize --tbSize=$tbSize >> $OUTPUT
		done
	done
fi

if [ $STEP -eq 3 ] ; then
	echo "# EXP.1 BASIC" >> $OUTPUT
	for APP in HEAT2D;
	do
		#./switchApp $APP 0
		for tileWidth in 256 512 1024;
		do
			for tileHeight in 256 512 1024;
			do
				nvprof --print-gpu-trace $EXEC  --mode=2 rowsPerBlock=1 --width=$tileWidth --height=$tileHeight --tileWidth=$tileWidth --tileHeight=$tileHeight --tbSize=1024 --nSM=1 2>> $OUTPUT

			done
		done
	done
fi
